name: deploy-search

on:
  workflow_dispatch:
  push:
    branches: ['master']
    paths:
      - 'src/SearchService/**'

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 497968533970.dkr.ecr.us-east-2.amazonaws.com/carsties
  IMAGE_NAME: search-svc
  DOCKERFILE: src/IdentityService/Dockerfile
  DEPLOYMENT_NAME: search-svc
  HELM_RELEASE_NAME: search-svc
  CHART_PATH: ./search-svc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}
      - name: Build and tag Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME -f $DOCKERFILE .
          docker tag $ECR_REGISTRY/$IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest
      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Update kubeconfig for AWS EKS
        run: aws eks update-kubeconfig --name carsties --region ${{ env.AWS_REGION }}
      - name: Deploy using Helm chart
        run: |
          helm upgrade --install $HELM_RELEASE_NAME $CHART_PATH \
            --set image.repository=$ECR_REGISTRY/$IMAGE_NAME \
            --set image.tag=latest \
            --set deployment.name=${{ env.DEPLOYMENT_NAME }} \
            --namespace default \
              --wait --timeout 300s
